In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import math
import warnings
warnings.filterwarnings('ignore')

# Loading movie datasets

In [2]:
movie=pd.read_csv('tmdb_5000_movies.csv')
movie.head(5)

,budget,genres,homepage,id,keywords,original_language,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",10-12-2009,2787965087,162.0,Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",19-05-2007,961000000,169.0,Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",26-10-2015,880674609,148.0,Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",16-07-2012,1084939099,165.0,Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",07-03-2012,284139100,132.0,Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [3]:
credit=pd.read_csv('tmdb_5000_credits.csv')
credit.head(5)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

# data exploring

In [4]:
movie.shape

(4803, 18)

In [5]:
credit.shape

(4803, 4)

In [6]:
movie.dtypes

budget                    int64
genres                   object
homepage                 object
id                        int64
keywords                 object
original_language        object
overview                 object
popularity              float64
production_companies     object
production_countries     object
release_date             object
revenue                   int64
runtime                 float64
status                   object
tagline                  object
title                    object
vote_average            float64
vote_count                int64
dtype: object

In [7]:
credit.dtypes

movie_id     int64
title       object
cast        object
crew        object
dtype: object

In [8]:
movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   overview              4800 non-null   object
 7   popularity            4803 non-null   float64
 8   production_companies  4803 non-null   object
 9   production_countries  4803 non-null   object
 10  release_date          4802 non-null   object
 11  revenue               4803 non-null   int64
 12  runtime               4801 non-null   float64
 13  status                4803 non-null   object
 14  tagline               3959 non-null   object
 15  title                 4803 non-null   object
 16  vote_average          4803 non-null   float64
 17  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(11)
memory usage: 675.6+ KB

In [9]:
credit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4803 non-null   int64
 1   title     4803 non-null   object
 2   cast      4803 non-null   object
 3   crew      4803 non-null   object
dtypes: int64(1), object(3)
memory usage: 150.2+ KB

# Cleaning messy data

In [10]:
import json
def clean_text(data):
    if isinstance(data, str):
        try:
            data = json.loads(data)
        except json.JSONDecodeError:
            try:
                data = json.loads(data.replace("'", '"'))
            except:
                return ''

 
    if isinstance(data, list):
        names = [d.get('name', '') for d in data if isinstance(d, dict)]
        text = ','.join(names)
    else:
        text = str(data)

   
    cleaned = ''.join(ch for ch in text if ch.isalnum() or ch in [',', ' '])
    cleaned = ' '.join(cleaned.split()).strip(' ,')
    return cleaned


movie['genres'] = movie['genres'].apply(clean_text)
movie['keywords'] = movie['keywords'].apply(clean_text)
movie['production_companies'] = movie['production_companies'].apply(clean_text)
movie['production_countries'] = movie['production_countries'].apply(clean_text)

movie.head()

,budget,genres,homepage,id,keywords,original_language,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,status,tagline,title,vote_average,vote_count
0,237000000,"Action,Adventure,Fantasy,Science Fiction",http://www.avatarmovie.com/,19995,"culture clash,future,space war,space colony,so...",en,"In the 22nd century, a paraplegic Marine is di...",150.437577,"Ingenious Film Partners,Twentieth Century Fox ...","United States of America,United Kingdom",10-12-2009,2787965087,162.0,Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"Adventure,Fantasy,Action",http://disney.go.com/disneypictures/pirates/,285,"ocean,drug abuse,exotic island,east india trad...",en,"Captain Barbossa, long believed to be dead, ha...",139.082615,"Walt Disney Pictures,Jerry Bruckheimer Films,S...",United States of America,19-05-2007,961000000,169.0,Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"Action,Adventure,Crime",http://www.sonypictures.com/movies/spectre/,206647,"spy,based on novel,secret agent,sequel,mi6,bri...",en,A cryptic message from Bond’s past sends him o...,107.376788,"Columbia Pictures,Danjaq,B24","United Kingdom,United States of America",26-10-2015,880674609,148.0,Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"Action,Crime,Drama,Thriller",http://www.thedarkknightrises.com/,49026,"dc comics,crime fighter,terrorist,secret ident...",en,Following the death of District Attorney Harve...,112.312950,"Legendary Pictures,Warner Bros,DC Entertainmen...",United States of America,16-07-2012,1084939099,165.0,Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"Action,Adventure,Science Fiction",http://movies.disney.com/john-carter,49529,"based on novel,mars,medallion,space travel,pri...",en,"John Carter is a war-weary, former military ca...",43.926995,Walt Disney Pictures,United States of America,07-03-2012,284139100,132.0,Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [11]:
def clean_text(text):
    if isinstance(text, str):
        try:
            data = json.loads(text)
        except json.JSONDecodeError:
            try:
                data = json.loads(text.replace("'", '"'))
            except:
                data = text 

        if isinstance(data, list):
            names = [d.get('name', '') for d in data if isinstance(d, dict)]
            text = ','.join(names)
        else:
            text = str(data)
        cleaned = ''.join(ch for ch in text if ch.isalnum() or ch in [',', ' '])
        cleaned = ' '.join(cleaned.split()).strip(' ,')
        return cleaned
    return text

credit['title'] = credit['title'].apply(clean_text)
credit['cast'] = credit['cast'].apply(clean_text)


credit.head()

,movie_id,title,cast,crew
0,19995,Avatar,"Sam Worthington,Zoe Saldana,Sigourney Weaver,S...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean At Worlds End,"Johnny Depp,Orlando Bloom,Keira Knightley,Stel...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"Daniel Craig,Christoph Waltz,Léa Seydoux,Ralph...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"Christian Bale,Michael Caine,Gary Oldman,Anne ...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"Taylor Kitsch,Lynn Collins,Samantha Morton,Wil...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [12]:
import json

def safe_json_load(x):
    if isinstance(x, list):
        return x
    if pd.isna(x) or x in ['', '[]', 'None', None]:
        return []
    try:
        return json.loads(x)
    except:
        try:
            return json.loads(x.replace("'", '"'))
        except:
            return []


def get_crew_name(crew_list, job_title):
    for person in crew_list:
        if isinstance(person, dict):
            if person.get('job') == job_title or person.get('Job') == job_title:
                return person.get('name') or person.get('Name') or "Unknown"
    return "Unknown"


credit['crew'] = credit['crew'].apply(safe_json_load)

roles = [
    'Director', 'Editor', 'Production Design', 'Art Direction',
    'Costume Design', 'Original Music Composer', 'Director of Photography'
]

for role in roles:
    col_name = role.lower().replace(' ', '_')
    credit[col_name] = credit['crew'].apply(lambda x: get_crew_name(x, role))


credit.head(5)

,movie_id,title,cast,crew,director,editor,production_design,art_direction,costume_design,original_music_composer,director_of_photography
0,19995,Avatar,"Sam Worthington,Zoe Saldana,Sigourney Weaver,S...","[{'credit_id': '52fe48009251416c750aca23', 'de...",James Cameron,Stephen E. Rivkin,Rick Carter,Andrew Menzies,Deborah Lynn Scott,James Horner,Mauro Fiore
1,285,Pirates of the Caribbean At Worlds End,"Johnny Depp,Orlando Bloom,Keira Knightley,Stel...","[{'credit_id': '52fe4232c3a36847f800b579', 'de...",Gore Verbinski,Stephen E. Rivkin,Rick Heinrichs,John Dexter,Liz Dann,Hans Zimmer,Dariusz Wolski
2,206647,Spectre,"Daniel Craig,Christoph Waltz,Léa Seydoux,Ralph...","[{'credit_id': '54805967c3a36829b5002c41', 'de...",Sam Mendes,Lee Smith,Dennis Gassner,Neal Callow,Jany Temime,Thomas Newman,Hoyte van Hoytema
3,49026,The Dark Knight Rises,"Christian Bale,Michael Caine,Gary Oldman,Anne ...","[{'credit_id': '52fe4781c3a36847f81398c3', 'de...",Christopher Nolan,Lee Smith,Nathan Crowley,Robert Woodruff,Lindy Hemming,Hans Zimmer,Wally Pfister
4,49529,John Carter,"Taylor Kitsch,Lynn Collins,Samantha Morton,Wil...","[{'credit_id': '52fe479ac3a36847f813eaa3', 'de...",Andrew Stanton,Eric Zumbrunnen,Nathan Crowley,Robert Woodruff,Mayes C. Rubeo,Unknown,Daniel Mindel

In [13]:
credit.drop('crew',axis=1,inplace=True)

In [14]:
credit.head()

,movie_id,title,cast,director,editor,production_design,art_direction,costume_design,original_music_composer,director_of_photography
0,19995,Avatar,"Sam Worthington,Zoe Saldana,Sigourney Weaver,S...",James Cameron,Stephen E. Rivkin,Rick Carter,Andrew Menzies,Deborah Lynn Scott,James Horner,Mauro Fiore
1,285,Pirates of the Caribbean At Worlds End,"Johnny Depp,Orlando Bloom,Keira Knightley,Stel...",Gore Verbinski,Stephen E. Rivkin,Rick Heinrichs,John Dexter,Liz Dann,Hans Zimmer,Dariusz Wolski
2,206647,Spectre,"Daniel Craig,Christoph Waltz,Léa Seydoux,Ralph...",Sam Mendes,Lee Smith,Dennis Gassner,Neal Callow,Jany Temime,Thomas Newman,Hoyte van Hoytema
3,49026,The Dark Knight Rises,"Christian Bale,Michael Caine,Gary Oldman,Anne ...",Christopher Nolan,Lee Smith,Nathan Crowley,Robert Woodruff,Lindy Hemming,Hans Zimmer,Wally Pfister
4,49529,John Carter,"Taylor Kitsch,Lynn Collins,Samantha Morton,Wil...",Andrew Stanton,Eric Zumbrunnen,Nathan Crowley,Robert Woodruff,Mayes C. Rubeo,Unknown,Daniel Mindel

In [15]:
movie.drop_duplicates()
credit.drop_duplicates()

,movie_id,title,cast,director,editor,production_design,art_direction,costume_design,original_music_composer,director_of_photography
0,19995,Avatar,"Sam Worthington,Zoe Saldana,Sigourney Weaver,S...",James Cameron,Stephen E. Rivkin,Rick Carter,Andrew Menzies,Deborah Lynn Scott,James Horner,Mauro Fiore
1,285,Pirates of the Caribbean At Worlds End,"Johnny Depp,Orlando Bloom,Keira Knightley,Stel...",Gore Verbinski,Stephen E. Rivkin,Rick Heinrichs,John Dexter,Liz Dann,Hans Zimmer,Dariusz Wolski
2,206647,Spectre,"Daniel Craig,Christoph Waltz,Léa Seydoux,Ralph...",Sam Mendes,Lee Smith,Dennis Gassner,Neal Callow,Jany Temime,Thomas Newman,Hoyte van Hoytema
3,49026,The Dark Knight Rises,"Christian Bale,Michael Caine,Gary Oldman,Anne ...",Christopher Nolan,Lee Smith,Nathan Crowley,Robert Woodruff,Lindy Hemming,Hans Zimmer,Wally Pfister
4,49529,John Carter,"Taylor Kitsch,Lynn Collins,Samantha Morton,Wil...",Andrew Stanton,Eric Zumbrunnen,Nathan Crowley,Robert Woodruff,Mayes C. Rubeo,Unknown,Daniel Mindel
...,...,...,...,...,...,...,...,...,...,...
4798,9367,El Mariachi,"Carlos Gallardo,Jaime de Hoyos,Peter Marquardt...",Robert Rodriguez,Robert Rodriguez,Unknown,Unknown,Unknown,Unknown,Robert Rodriguez
4799,72766,Newlyweds,"Edward Burns,Kerry Bishé,Marsha Dietlein,Caitl...",Edward Burns,Janet Gaynor,Unknown,Unknown,Unknown,Unknown,Unknown
4800,231617,"Signed, Sealed, Delivered","Eric Mabius,Kristin Booth,Crystal Lowe,Geoff G...",Scott Smith,Lisa Binkley,Renee Read,Unknown,Carla Hetland,Hal Beckett,Adam Sliwinski
4801,126186,Shanghai Calling,"Daniel Henney,Eliza Coupe,Bill Paxton,Alan Ruc...",Daniel Hsia,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
4802,25975,My Date with Drew,"Drew Barrymore,Brian Herzlinger,Corey Feldman,...",Brian Herzlinger,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown

# Missing value treatment

In [16]:
import ast
def try_literal_eval(x):
    if isinstance(x, str):
        s = x.strip()
        if s in ('', 'None', 'nan', 'NaN', '<NA>', '\\N', '\\n'):
            return s
        if s[0] in ('[','{','(','"',"'"):
            try:
                return ast.literal_eval(s)
            except Exception:
                return x
    return x


def normalize_empty_to_nan(x):
    x = try_literal_eval(x)
    if x is None:
        return np.nan
    if isinstance(x, float) and np.isnan(x):
        return np.nan
    if isinstance(x, (list, tuple, set)) and len(x) == 0:
        return np.nan
    if isinstance(x, dict) and len(x) == 0:
        return np.nan
    if isinstance(x, str) and x.strip() in ('', 'None', 'nan', 'NaN', '<NA>', '\\N', '\\n', '[]', '{}'):
        return np.nan
    return x

obj_cols = movie.select_dtypes(include=['object']).columns.tolist()
for col in obj_cols:
    movie[col] = movie[col].apply(normalize_empty_to_nan)


print("Columns processed:", obj_cols)
print("\nmissing-value counts:")
print(movie.isna().sum().sort_values(ascending=False))

Columns processed: ['genres', 'homepage', 'keywords', 'original_language', 'overview', 'production_companies', 'production_countries', 'release_date', 'status', 'tagline', 'title']

missing-value counts:
homepage                3091
tagline                  844
keywords                 412
production_companies     351
production_countries     174
genres                    28
overview                   4
runtime                    2
release_date               1
budget                     0
popularity                 0
original_language          0
id                         0
revenue                    0
status                     0
title                      0
vote_average               0
vote_count                 0
dtype: int64

In [17]:
movie.drop(columns=['homepage'], inplace=True)
fill_unknown_cols = ['tagline', 'keywords', 'production_companies','production_countries', 'genres', 'overview']
movie[fill_unknown_cols] = movie[fill_unknown_cols].fillna("Unknown")

if 'runtime' in movie.columns:
    movie['runtime'].fillna(movie['runtime'].median(), inplace=True)
if 'release_date' in movie.columns:
    movie['release_date'].fillna(movie['release_date'].mode()[0], inplace=True)

print("Missing values handled successfully:")
print(movie.isna().sum())

Missing values handled successfully:
budget                  0
genres                  0
id                      0
keywords                0
original_language       0
overview                0
popularity              0
production_companies    0
production_countries    0
release_date            0
revenue                 0
runtime                 0
status                  0
tagline                 0
title                   0
vote_average            0
vote_count              0
dtype: int64

In [18]:
import ast
def try_literal_eval(x):
    if isinstance(x, str):
        s = x.strip()
        if s in ('', 'None', 'nan', 'NaN', '<NA>', '\\N', '\\n'):
            return s
        if s[0] in ('[','{','(','"',"'"):
            try:
                return ast.literal_eval(s)
            except Exception:
                return x
    return x


def normalize_empty_to_nan(x):
    x = try_literal_eval(x)
  
    if x is None:
        return np.nan
    if isinstance(x, float) and np.isnan(x):
        return np.nan
    if isinstance(x, (list, tuple, set)) and len(x) == 0:
        return np.nan
    if isinstance(x, dict) and len(x) == 0:
        return np.nan
    if isinstance(x, str) and x.strip() in ('', 'None', 'nan', 'NaN', '<NA>', '\\N', '\\n', '[]', '{}'):
        return np.nan
    return x

obj_cols = credit.select_dtypes(include=['object']).columns.tolist()

for col in obj_cols:
    credit[col] = credit[col].apply(normalize_empty_to_nan)


print("Columns processed:", obj_cols)
print("\nmissing-value counts :")
print(credit.isna().sum().sort_values(ascending=False))

Columns processed: ['title', 'cast', 'director', 'editor', 'production_design', 'art_direction', 'costume_design', 'original_music_composer', 'director_of_photography']

missing-value counts :
cast                       43
movie_id                    0
title                       0
director                    0
editor                      0
production_design           0
art_direction               0
costume_design              0
original_music_composer     0
director_of_photography     0
dtype: int64

In [19]:
credit['cast'].fillna('Unknown', inplace=True)
print(" Missing values handled successfully:")
print(credit.isnull().sum())

 Missing values handled successfully:
movie_id                   0
title                      0
cast                       0
director                   0
editor                     0
production_design          0
art_direction              0
costume_design             0
original_music_composer    0
director_of_photography    0
dtype: int64

# Outlier treatment

In [20]:
for col in movie.select_dtypes(include=['float64', 'int64']).columns:
    Q1 = movie[col].quantile(0.25)
    Q3 = movie[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_limit = Q1 - 1.5 * IQR
    upper_limit = Q3 + 1.5 * IQR
    outliers = movie[(movie[col] < lower_limit) | (movie[col] > upper_limit)]
    print(f"\nColumn: {col}")
    print(f"Number of outliers: {outliers.shape[0]}")
    print("-" * 50)
    median = movie[col].median()
    movie[col] = np.where((movie[col] < lower_limit) | (movie[col] > upper_limit), median, movie[col])
    outliers = movie[(movie[col] < lower_limit) | (movie[col] > upper_limit)]
    print(f"Column: {col}")
    print(f"Number of outliers: {outliers.shape[0]}")

print("Outliers treated successfully")

Column: budget
Number of outliers: 321
--------------------------------------------------
Column: budget
Number of outliers: 0

Column: id
Number of outliers: 704
--------------------------------------------------
Column: id
Number of outliers: 0

Column: popularity
Number of outliers: 275
--------------------------------------------------
Column: popularity
Number of outliers: 0

Column: revenue
Number of outliers: 472
--------------------------------------------------
Column: revenue
Number of outliers: 0

Column: runtime
Number of outliers: 201
--------------------------------------------------
Column: runtime
Number of outliers: 0

Column: vote_average
Number of outliers: 156
--------------------------------------------------
Column: vote_average
Number of outliers: 0

Column: vote_count
Number of outliers: 504
--------------------------------------------------
Column: vote_count
Number of outliers: 0
Outliers treated successfully

In [21]:
df=pd.merge(movie,credit,on='title',how='inner')
df.head(5)

,budget,genres,id,keywords,original_language,overview,popularity,production_companies,production_countries,release_date,...,vote_count,movie_id,cast,director,editor,production_design,art_direction,costume_design,original_music_composer,director_of_photography
0,15000000.0,"Action,Adventure,Fantasy,Science Fiction",19995.0,"culture clash,future,space war,space colony,so...",en,"In the 22nd century, a paraplegic Marine is di...",12.921594,"Ingenious Film Partners,Twentieth Century Fox ...","United States of America,United Kingdom",10-12-2009,...,235.0,19995,"Sam Worthington,Zoe Saldana,Sigourney Weaver,S...",James Cameron,Stephen E. Rivkin,Rick Carter,Andrew Menzies,Deborah Lynn Scott,James Horner,Mauro Fiore
1,15000000.0,"Action,Adventure,Crime",14629.0,"spy,based on novel,secret agent,sequel,mi6,bri...",en,A cryptic message from Bond’s past sends him o...,12.921594,"Columbia Pictures,Danjaq,B24","United Kingdom,United States of America",26-10-2015,...,235.0,206647,"Daniel Craig,Christoph Waltz,Léa Seydoux,Ralph...",Sam Mendes,Lee Smith,Dennis Gassner,Neal Callow,Jany Temime,Thomas Newman,Hoyte van Hoytema
2,15000000.0,"Action,Crime,Drama,Thriller",49026.0,"dc comics,crime fighter,terrorist,secret ident...",en,Following the death of District Attorney Harve...,12.921594,"Legendary Pictures,Warner Bros,DC Entertainmen...",United States of America,16-07-2012,...,235.0,49026,"Christian Bale,Michael Caine,Gary Oldman,Anne ...",Christopher Nolan,Lee Smith,Nathan Crowley,Robert Woodruff,Lindy Hemming,Hans Zimmer,Wally Pfister
3,15000000.0,"Action,Adventure,Science Fiction",49529.0,"based on novel,mars,medallion,space travel,pri...",en,"John Carter is a war-weary, former military ca...",43.926995,Walt Disney Pictures,United States of America,07-03-2012,...,235.0,49529,"Taylor Kitsch,Lynn Collins,Samantha Morton,Wil...",Andrew Stanton,Eric Zumbrunnen,Nathan Crowley,Robert Woodruff,Mayes C. Rubeo,Unknown,Daniel Mindel
4,15000000.0,"Animation,Family",38757.0,"hostage,magic,horse,fairy tale,musical,princes...",en,When the kingdom's most wanted-and most charmi...,48.681969,"Walt Disney Pictures,Walt Disney Animation Stu...",United States of America,24-11-2010,...,235.0,38757,"Zachary Levi,Mandy Moore,Donna Murphy,Ron Perl...",Byron Howard,Tim Mertens,Douglas Rogers,David Goetz,Unknown,Alan Menken,Unknown

# Saving the dataset

In [23]:
movie.to_csv(r'D:\c10\movie_preprocessed.csv')

In [24]:
credit.to_csv(r'D:\c10\credit_preprocessed.csv')

In [25]:
df.to_csv(r'D:\c10\joined_dataset.csv')

# Scaling

In [26]:
movie=pd.read_csv('movie_preprocessed.csv')
credit=pd.read_csv('credit_preprocessed.csv')
movie.drop(columns=['Unnamed: 0'], inplace=True)
credit.drop(columns=['Unnamed: 0'], inplace=True)

In [27]:
from sklearn.preprocessing import MinMaxScaler,StandardScaler
numeric_movie=movie.select_dtypes(include=['number'])
scaler=StandardScaler()
movie_scale=scaler.fit_transform(numeric_movie)
movie_scaled=pd.DataFrame(movie_scale,columns=numeric_movie.columns)
movie_scaled

,budget,id,popularity,revenue,runtime,vote_average,vote_count
0,-0.225206,-0.093915,-0.224718,-0.350042,-0.149503,1.141199,-0.262747
1,-0.225206,-0.873016,-0.224718,-0.350042,-0.149503,0.789533,-0.262747
2,-0.225206,-0.306023,-0.224718,-0.350042,2.744882,0.086202,-0.262747
3,-0.225206,1.053629,-0.224718,-0.350042,-0.149503,1.610086,-0.262747
4,-0.225206,1.073512,1.884870,-0.350042,1.715767,-0.148242,-0.262747
...,...,...,...,...,...,...,...
4798,-0.869743,-0.514020,-0.132988,-0.673529,-1.564536,0.437868,-0.255044
4799,-0.878945,1.992029,-1.060177,-0.712073,-1.307257,-0.382686,-0.853283
4800,-0.879337,-0.306023,-1.005615,-0.712073,0.943931,0.906755,-0.850715
4801,-0.879337,4.103626,-1.045586,-0.712073,-0.471102,-0.617129,-0.848148
4802,-0.879337,0.142464,-0.972588,-0.712073,-0.985659,0.086202,-0.825040

In [29]:
movie_scaled.to_csv(r'D:\c10\movie_scaled.csv')

In [30]:
movie=pd.read_csv('movie_preprocessed.csv')
movie.drop(columns=['Unnamed: 0'], inplace=True)

In [33]:
import mysql.connector as sql
db=sql.connect(host='localhost',user='root',password='Annu@123#',database='course10')
cur=db.cursor()

In [34]:
cur = db.cursor()
cols = movie.columns.tolist()
column_definitions = ", ".join([f"`{col}` TEXT" for col in cols])
create_query = f"""
CREATE TABLE IF NOT EXISTS movie_table (
    {column_definitions}
)
"""

cur.execute(create_query)
placeholders = ", ".join(["%s"] * len(cols))
insert_query = f"INSERT INTO movie_table ({', '.join(cols)}) VALUES ({placeholders})"
data = [tuple(row) for row in movie.values]
cur.executemany(insert_query, data)
db.commit()